// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypivkqnilwnfuvdwvowk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwaXZrcW5pbHduZnV2ZHd2b3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTE0NzEsImV4cCI6MjA3MTI4NzQ3MX0.QaKP_f7IPVvFAEOZgEFWjSpkIVeyQXUJiLWDrOK50ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});